add_newline = false
[line_break]
disabled = true
[shell]
 #fish_indicator = "ïœ¹"
 powershell_indicator = ">_"
 unknown_indicator = "mystery shell"
 bash_indicator="><"
 zsh_indicator="<z>"
 style = " Purple Bold"
 disabled = false

[character]
success_symbol = "[â¯](purple) "
error_symbol = "[âœ—](bold yellow) "

[python]
symbol = "ğŸ " 
